/* SimpleCL, error functions
 * Copyright (C) 2014 Bruno Jiménez
 * 
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <CL/cl.h>
#include <stdio.h>

#define CASE_ERR(ec) case ec: fprintf(stderr, #ec"\n"); break;

void sclPrintErrorFlags(cl_int flag)
{
	switch (flag)
	{
		CASE_ERR(CL_BUILD_PROGRAM_FAILURE)

		CASE_ERR(CL_COMPILER_NOT_AVAILABLE)

		CASE_ERR(CL_DEVICE_NOT_AVAILABLE)
		CASE_ERR(CL_DEVICE_NOT_FOUND)

		CASE_ERR(CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST)

		CASE_ERR(CL_IMAGE_FORMAT_MISMATCH)
		CASE_ERR(CL_IMAGE_FORMAT_NOT_SUPPORTED)

		CASE_ERR(CL_INVALID_ARG_INDEX)
		CASE_ERR(CL_INVALID_ARG_SIZE)
		CASE_ERR(CL_INVALID_ARG_VALUE)
		CASE_ERR(CL_INVALID_BINARY)
		CASE_ERR(CL_INVALID_BUFFER_SIZE)
		CASE_ERR(CL_INVALID_BUILD_OPTIONS)
		CASE_ERR(CL_INVALID_COMMAND_QUEUE)
		CASE_ERR(CL_INVALID_CONTEXT)
		CASE_ERR(CL_INVALID_DEVICE)
		CASE_ERR(CL_INVALID_DEVICE_TYPE)
		CASE_ERR(CL_INVALID_EVENT)
		CASE_ERR(CL_INVALID_EVENT_WAIT_LIST)
		CASE_ERR(CL_INVALID_GL_OBJECT)
		CASE_ERR(CL_INVALID_GLOBAL_OFFSET)
		CASE_ERR(CL_INVALID_GLOBAL_WORK_SIZE)
		CASE_ERR(CL_INVALID_HOST_PTR)
		CASE_ERR(CL_INVALID_IMAGE_FORMAT_DESCRIPTOR)
		CASE_ERR(CL_INVALID_IMAGE_SIZE)
		CASE_ERR(CL_INVALID_KERNEL)
		CASE_ERR(CL_INVALID_KERNEL_ARGS)
		CASE_ERR(CL_INVALID_KERNEL_DEFINITION)
		CASE_ERR(CL_INVALID_KERNEL_NAME)
		CASE_ERR(CL_INVALID_MEM_OBJECT)
		CASE_ERR(CL_INVALID_MIP_LEVEL)
		CASE_ERR(CL_INVALID_OPERATION)
		CASE_ERR(CL_INVALID_PLATFORM)
		CASE_ERR(CL_INVALID_PROGRAM)
		CASE_ERR(CL_INVALID_PROGRAM_EXECUTABLE)
		CASE_ERR(CL_INVALID_PROPERTY)
		CASE_ERR(CL_INVALID_QUEUE_PROPERTIES)
		CASE_ERR(CL_INVALID_SAMPLER)
		CASE_ERR(CL_INVALID_VALUE)
		CASE_ERR(CL_INVALID_WORK_DIMENSION)
		CASE_ERR(CL_INVALID_WORK_GROUP_SIZE)
		CASE_ERR(CL_INVALID_WORK_ITEM_SIZE)

		CASE_ERR(CL_MAP_FAILURE)

		CASE_ERR(CL_MEM_COPY_OVERLAP)
		CASE_ERR(CL_MEM_OBJECT_ALLOCATION_FAILURE)

		CASE_ERR(CL_MISALIGNED_SUB_BUFFER_OFFSET)

		CASE_ERR(CL_OUT_OF_HOST_MEMORY)
		CASE_ERR(CL_OUT_OF_RESOURCES)

		CASE_ERR(CL_PROFILING_INFO_NOT_AVAILABLE)
		default:
			fprintf( stderr, "Unknown error code: %d\n",flag);
	}
}

#undef CASE_ERR
